# Generated by Django 4.1.5 on 2023-01-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_by', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100000)),
            ],
        ),
    ]
